apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-upgrade-consumer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "istio-upgrade-consumer.podlabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Release.Name }}
      containers:
      - image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        name: istio-upgrade-consumer
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        resources: {{ .Values.resources | toYaml  | nindent 10 }}

