apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-upgrade-consumer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: {{ .Values.configuration.receiverHTTPPort | int }}
    protocol: TCP
    targetPort: {{ .Values.configuration.receiverHTTPPort | int }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: ClusterIP