deployment:
  image: "ghcr.io/gopaytech/istio-upgrade-consumer"
  tag: "master"
  replicas: 2

resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 256m
    memory: 256Mi

serviceAccount:
  imagePullSecrets: []
  automountServiceAccountToken: true

podLabels: {}

configuration:
  clusterName: "my-cluster"
  clusterEnvironment: "production"
  receiverMode: "http"
  receiverHTTPPort: "8080"
  storageMode: "configmap"
  storageConfigMapName: "istio-auto-upgrade-config"
  storageConfigMapNamespace: "istio-system"
  productionWaitingDay: "28"
  nonProductionWaitingDay: "7"
  timeLocation: "Asia/Jakarta"
  timeFormat: "2006-01-02"