apiVersion: v1
entries:
  istio-upgrade-consumer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-09-28T23:32:23.030139+07:00"
    description: Consumer for Istio Upgrade tooling to receive events related to Istio
      upgrade
    digest: c59e9f919b01632a89d2ea784d702678745cf63ae91488df8c917c2d5ca3b294
    home: https://github.com/gopaytech/istio-upgrade-consumer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-consumer
    type: application
    urls:
    - istio-upgrade-consumer-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-28T23:32:23.028771+07:00"
